on:
 push:
jobs:
  my_job:
   runs-on: ubuntu-latest
   steps:
     - name: deploy to staging
       id: test
       run: echo ${{ secrets.SECRET1 }}
     - name: test2
       if: steps.test.outcome == "hola"
       run: echo "vamooo ñuebel"
